# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e27a9126023413a598c8bdb831d57d1a18e2b584e6898a2eb21a976f39516d9e26eeeffa308c956ee97125f878d31be71377287c3bc5df64935223efe307a48

test:
  secret_key_base: 41787ecb343dfcef6f8bf12ef908175905abeb7e70e9fe7f9ab359180e16b9243313d28822c93556fbd610eb0df5878264e8e9a37faaa38a12fe51ee6db08aa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
